# Generated by Django 5.2.14 on 2026-05-18 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_rename_nm_subject_name_remove_subject_days_and_more'),
        ('accounts', '0003_studentprofile_phone_studentprofile_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='program_enrolled',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.course'),
        ),
    ]
