# Generated by Django 5.2.14 on 2026-05-18 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_instructor_subject'),
        ('scheduling', '0002_remove_section_room_remove_section_time_slot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='nm',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='days',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='et',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='instId',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='room',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='secId',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='st',
        ),
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ClassOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(max_length=50)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_offerings', to='academics.instructor')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='scheduling.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='academics.subject')),
            ],
        ),
    ]
