# Generated by Django 5.2.14 on 2026-05-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_rename_nm_subject_name_remove_subject_days_and_more'),
        ('scheduling', '0002_remove_section_room_remove_section_time_slot_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='classoffering',
            constraint=models.UniqueConstraint(fields=('subject', 'section'), name='unique_subject_per_section'),
        ),
    ]
