# Generated by Django 5.2.14 on 2026-05-18 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='room',
        ),
        migrations.RemoveField(
            model_name='section',
            name='time_slot',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
